# Generated by Django 3.2.5 on 2021-07-22 21:03

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('daily_rate_range', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('availability', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('1/2 days/wk', '1/2 days/wk'), ('3/4 days/wk', '3/4 days/wk'), ('full time', 'full time')], max_length=32), size=None)),
                ('location', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('onsite', 'onsite'), ('remote', 'remote'), ('mixed', 'mixed')], max_length=32), size=None)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juggle.business')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('daily_rate_range', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('availability', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('1/2 days/wk', '1/2 days/wk'), ('3/4 days/wk', '3/4 days/wk'), ('full time', 'full time')], max_length=32), size=None)),
                ('location', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('onsite', 'onsite'), ('remote', 'remote'), ('mixed', 'mixed')], max_length=32), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juggle.job')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juggle.professional')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(to='juggle.Skill'),
        ),
        migrations.CreateModel(
            name='BusinessAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juggle.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
