version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=juggle
      - POSTGRES_USER=juggle
      - POSTGRES_PASSWORD=juggle
    volumes:
      - local_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
    volumes:
      - ".:/code/"
    restart: always

  gateway:
    image: nginx:1.21.1
    depends_on:
      - api
    ports:
      - '80:80'
    volumes:
      - './nginx.juggle.conf:/etc/nginx/conf.d/default.conf'
    restart: always

volumes:
  local_db_data: {}
