version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    depends_on:
      - db
    volumes:
      - ".:/code/"
    ports:
      - "8000:8000"
    restart: always

  gateway:
    image: nginx:1.21.1
    depends_on:
      - api
    ports:
      - '80:80'
    volumes:
      - './nginx.juggle.conf:/etc/nginx/conf.d/default.conf'
    restart: always

volumes:
  local_postgres_data: {}
